### ISSUE TITLE
Remove `ArrayView.h`

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#171]
Class `ArrayView.h` seems like duplicate of `std::vector<std::shared_ptr...>`. Can I remove it?

**Comment by garth-wells** [comment]
I would suggest waiting until `SystemAssembler` is removed. It's hard to unpick `ArrayView` in `SystemAssembler` (which is why it hasn't been removed yet).

`ArrayView` was designed to be a very lightweight, safe wrapper around raw pointers. `std::shared_ptr` can be quite expensive. `EigenMap` can be used in place of  `ArrayView`.

**Comment by michalhabera** [comment]
Ok, using `EigenMap` makes very good sense for this. Lets keep this issue for record.

**Comment by garth-wells** [comment]
Fixed in #318.
