### ISSUE TITLE
Remove `Point.h/.cpp`

### ISSUE THREAD

**Issue by michalhabera** [FEniCS/dolfinx#196]
`Point.h` is just triple of `double` with trivial operations defined for it. 
Could be replaced with Eigen array, which maps automatically to numpy arrays through pybind.

**Comment by chrisrichardson** [comment]
Yes. I started on this before. Unfortunately `Point` is very pervasive, and it is quite a big task.

**Comment by michalhabera** [comment]
I can imagine ;) Carry on!

**Comment by chrisrichardson** [comment]
This turns out to be quite a difficult task: suggest breaking it up into smaller pieces, first of which would
be to make the I/O more agnostic about the geometry storage. At the moment, it assumes the points are linearly stored in memory, but if we go to all points being 3D, we will need to stride over the data to get 2D or 1D datasets for I/O.

**Comment by chrisrichardson** [comment]
Now done
