### ISSUE TITLE
Using the method compute_point_values() 

### ISSUE THREAD

**Issue by MaxDangVu136** [FEniCS/dolfinx#2136]
Hi there, 

I have recently cloned an update version of the dolfinx package. This has resulted in some changes to my function calls using the Python API. One of the methods affected is **u.compute_point_values()** where u is the mesh deformation used to warp the mesh grid in showing how a mechanical mesh deforms in the simulation (this deformation is of type: dolfinx.fem.function.Function). 

I seem to cannot find this method, which provides the following error when run: **AttributeError: 'Function' object has no attribute 'compute_point_values'** for this code block. 

```
def plot_deformation(meshio_mesh, uh):
    print(type(uh))
    mesh = meshio_mesh
    initial_points = mesh.geometry.x
    pyvista.start_xvfb(wait=0.05)
    topology, cell_types, geometry = dolfinx.plot.create_vtk_mesh(mesh, mesh.topology.dim)
    grid = pyvista.UnstructuredGrid(topology, cell_types, geometry)
    
    p = pyvista.Plotter(notebook=True, window_size=[960,480]) #
    
    p.add_text("Deformed configuration", name="title", position="upper_edge")
    
    sargs = dict(title_font_size=20, label_font_size=16, shadow=True,
                n_labels=3, italic=True, fmt="%.1f", font_family="arial")
    
    grid["u"] = uh.compute_point_values().real
    actor_0 = p.add_mesh(grid, style="wireframe", color="k", scalar_bar_args=sargs)
    warped = grid.warp_by_vector("u", factor=1.5)
    actor_1 = p.add_mesh(warped, scalar_bar_args=sargs)
    
    p.show_axes()
    viewer = p.show(interactive='True', jupyter_backend='panel', return_viewer=True)
    return viewer, initial_points, grid["u"], warped
```

Here is the link to the method's API: https://fenicsproject.org/olddocs/dolfinx/dev/python/_modules/dolfinx/function.html#Function.compute_point_values. 

Please let me know why this is happening and how we can resolve it. Thank you and kind regards, 

Max Dang Vu

**Comment by jorgensd** [comment]
You are looking at old documentation, as indicated by the link [https://fenicsproject.org/olddocs/...](https://fenicsproject.org/olddocs/dolfinx/dev/python/_modules/dolfinx/function.html#Function.compute_point_values)
It shouldn't really exist, and I've made a separate issue at https://github.com/FEniCS/web/issues/87.

`compute_point_values` has been removed (https://github.com/FEniCS/dolfinx/pull/1990) due to the fact that is was very inefficient. 

Instead you should interpolate the function `uh` into the same space as your `Mesh`, which is a `ufl.Finite/Vector/TensorElement("Lagrange", mesh.ufl_cell(), mesh.geometry.cmap.degree)`. 

However, as you are using this for plotting with `pyvista` I would suggest having a look at:
https://jorgensd.github.io/dolfinx-tutorial/chapter2/linearelasticity_code.html
as it shows how to create a pyvista mesh based on the function space (as long as it is Lagrange based) and how to plot it.
