### ISSUE TITLE
Add `SLEPc` and `slepc4py` to the test environment

### ISSUE THREAD

**Issue by jorgensd** [FEniCS/dolfinx#2355]
We have tests relying on SLEPc: https://github.com/FEniCS/dolfinx/blob/621d1479adf1e1a8beb9eed86cc8ad3de963f223/python/test/unit/fem/test_fem_pipeline.py#L204
and future PRs using SLEPc: https://github.com/FEniCS/dolfinx/pull/2338
Without slepc/slepc4py in the CI, it will be tricky to maintain these tests/demos.

**Comment by garth-wells** [comment]
Isn't SLEPc and slepc4py already in the test images?
- https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile#L332
- https://github.com/FEniCS/dolfinx/blob/main/docker/Dockerfile#L348

**Comment by mikics** [comment]
I guess the problem is only with the RedHat check. The check for my SLEPc demo only failed there:

https://github.com/FEniCS/dolfinx/actions/runs/3008613372/jobs/4834438231

Indeed, in [Dockerfile.redhat](https://github.com/mikics/dolfinx/blob/main/docker/Dockerfile.redhat) file there is no reference to SLEPc.

**Comment by jhale** [comment]
The RedHat clone test image is meant to be very minimal (i.e. not include SLEPc) to check that DOLFINx and its tests really do run on a minimal set of dependencies.

The Ubuntu test image is more of a kitchen sink approach.
