### ISSUE TITLE
ffcx for Function name string including spaces

### ISSUE THREAD

**Issue by cmaurini** [FEniCS/dolfinx#2396]
Function name strings including spaces leads to a ffcx error and a strange error message. See the MWE below.

I have this issue with version 0.5.1

```
from dolfinx import fem, mesh
from ufl import dx
from mpi4py import MPI

msh = mesh.create_rectangle(
    comm=MPI.COMM_WORLD,
    points=((0.0, 0.0), (2.0, 1.0)),
    n=(1, 1),
    cell_type=mesh.CellType.triangle,
)
V = fem.FunctionSpace(msh, ("Lagrange", 1))
u_1 = fem.Function(V,name="without_space")
u_2 = fem.Function(V,name="with space")

# Works
fem.assemble_scalar(fem.form(2 * u_1 * dx))

# Does not work, with a incomprehensible error message
fem.assemble_scalar(fem.form(3 * u_2 * dx))
```

**Comment by jorgensd** [comment]
> Could you post the error message?
> 
> On a broader note, we should perhaps throw an exception if string contains spaces...

I think it is a general mistake that we use the function names in the generated code.

As we renumber the coefficients in the signature, we should just use this number, i.e. `f_0`, `f_1` etc

**Comment by michalhabera** [comment]
See https://github.com/FEniCS/ffcx/blob/main/ffcx/codegeneration/form.py#L111, which means function names must be a valid C identifier.

For forms, it is not really required we put function names into C object names, since we fetch them anyway with a string, but this is in place for expressions. Anyway, I think, as the code suggests, `ufcx_function_space` generation should be rewritten. I just made a simple check, https://github.com/FEniCS/ffcx/pull/539

**Comment by garth-wells** [comment]
@michalhabera does https://github.com/FEniCS/ffcx/pull/539 resolve this issue?

**Comment by michalhabera** [comment]
Yes, in a sense that an exception saying "Function name {name} must be a valid object identifier." will be thrown from ffcx.
