### ISSUE TITLE
[BUG]: gmshio.model_to_mesh causes segmentation violation for a half-disk-shaped mesh

### ISSUE THREAD

**Issue by Driy** [FEniCS/dolfinx#2456]
### How to reproduce the bug

gmshio.model_to_mesh crashes when building a simple geometry (half-disk) and adding physical groups for the domain bulk and the half-circle part of the domain boundary. This crash can be worked around by removing one of the physical groups, or by using gmsh.model.occ.add_circle_arc to build the geometry.

### Minimal Example (Python)

```Python
import gmsh

from dolfinx.io import gmshio
from mpi4py import MPI

R=1

# Initialize gmsh
gmsh.initialize()

p1 = gmsh.model.occ.add_point(-R, 0, 0)
p2 = gmsh.model.occ.add_point(R, 0, 0)

l1 = gmsh.model.occ.add_line(p2, p1)
l2 = gmsh.model.occ.add_circle(0,0,0,R,angle1=0,angle2=gmsh.pi) # <----

loop = gmsh.model.occ.add_curve_loop([l1,l2])
surf = gmsh.model.occ.add_plane_surface([loop])

gmsh.model.occ.synchronize()
gmsh.model.add_physical_group(1, [l2])        # <----
gmsh.model.add_physical_group(2, [surf])

# First mesh the lines
gmsh.model.mesh.generate(2)

# Get mesh geometry
mesh, cell_markers, facet_markers = gmshio.model_to_mesh(gmsh.model, MPI.COMM_SELF, 0, gdim=2)

# Close gmsh and clean up
gmsh.finalize()
```

### Output (Python)

```bash
[0]PETSC ERROR: ------------------------------------------------------------------------
[0]PETSC ERROR: Caught signal number 11 SEGV: Segmentation Violation, probably memory access out of range
[0]PETSC ERROR: Try option -start_in_debugger or -on_error_attach_debugger
[0]PETSC ERROR: or see https://petsc.org/release/faq/#valgrind
[0]PETSC ERROR: or try http://valgrind.org on GNU/linux and Apple MacOS to find memory corruption errors
[0]PETSC ERROR: configure using --with-debugging=yes, recompile, link, and run
[0]PETSC ERROR: to get more information on the crash.
[0]PETSC ERROR: Run with -malloc_debug to check if memory corruption is causing the crash.
```

### Version

0.5.1

### Installation

I installed DOLFINx via Anaconda on a MacBook Pro with M1 chip.

**Comment by jorgensd** [comment]
This is not a bug in the `dolfinx.io.gmshio` module, it is because `gmsh` redefines the boundaries of your mesh when you call `add_curve_loop`. 
I've illustrated this and corrected it 
```python
import dolfinx.io
from IPython import embed
import gmsh

from dolfinx.io import gmshio
from mpi4py import MPI

R = 1

# Initialize gmsh
gmsh.initialize()

p1 = gmsh.model.occ.add_point(-R, 0, 0)
p2 = gmsh.model.occ.add_point(R, 0, 0)

l1 = gmsh.model.occ.add_line(p2, p1)
l2 = gmsh.model.occ.add_circle(0, 0, 0, R, angle1=0, angle2=gmsh.pi)  # <----

loop = gmsh.model.occ.add_curve_loop([l1, l2])
surf = gmsh.model.occ.add_plane_surface([loop])

gmsh.model.occ.synchronize()
boundaries = gmsh.model.get_boundary([(2, surf)], oriented=False)
print(f"Actual boundaries: {boundaries}")
print(f"Old boundaries: {l1}, {l2}")
for boundary in boundaries:
    gmsh.model.add_physical_group(
        boundary[0], [boundary[1]], tag=boundary[1])

gmsh.model.add_physical_group(2, [surf], tag=3)

# First mesh the lines
gmsh.model.mesh.generate(2)

# Get mesh geometry
mesh, cell_markers, facet_markers = gmshio.model_to_mesh(
    gmsh.model, MPI.COMM_SELF, 0, gdim=2)

# Close gmsh and clean up
gmsh.finalize()
with dolfinx.io.XDMFFile(mesh.comm, "mesh2D.xdmf", "w") as xdmf:
    xdmf.write_mesh(mesh)
    xdmf.write_meshtags(facet_markers)
```
resulting in
```bash
Actual boundaries: [(1, 1), (1, 3)]
Old boundaries: 1, 2
Info    : Meshing 1D...
Info    : [  0%] Meshing curve 1 (Line)
Info    : [ 40%] Meshing curve 2 (Circle)
Info    : [ 70%] Meshing curve 3 (Circle)
Info    : Done meshing 1D (Wall 0.000507787s, CPU 0.000412s)
Info    : Meshing 2D...
Info    : Meshing surface 1 (Plane, Frontal-Delaunay)
Info    : Done meshing 2D (Wall 0.0058388s, CPU 0.005496s)
Info    : 73 nodes 131 elements
```
and 
![mesh2Dfacets](https://user-images.githubusercontent.com/8554300/203138739-79e753ff-3e99-4f50-b0a7-9d84def9636d.png)

**Comment by niravshah241** [comment]
@jorgensd The problem is that extract_geometry assumes the indices to start with 1. However, this assumption is hidden from the user. Also, it is not always possible to create meshes without any point or edge tags.  For example creating airfoil from many points.

Adding a good error message such as:
```
assert min(indices) == 1, "Consider removing all point tags in gmsh using gmsh.model.occ.remove ([0,point_tag_number])"
```
after 
```
indices, points, _ = model.mesh.getNodes()
```
in extract_geometry in gmshio will be helpful to users for understanding and for resolving the error.

Also consider similar changes for edge tags in extract_topology_and_markers.

**Comment by jorgensd** [comment]
@niravshah241 I do not see how this relates to the code above?
In the code above the issue is that a Physical Curve has been marked that is not in the actual mesh.

It is a fact that indices in MSH files generated by gmsh starts at 1. This is written in section 10.1 of: https://gmsh.info/doc/texinfo/gmsh.html#MSH-file-format
> Gmsh will create files with a continuous ordering of node and element tags, starting at 1.

I do not have an example where this is not the case, and without it I do not see a reason to adding this assertion.

**Comment by niravshah241** [comment]
@jorgensd The gmsh starts tags from 1. But indices in extract_geometry may not start at 1. See the issue reported here:
https://github.com/FEniCS/dolfinx/issues/2460
