### ISSUE TITLE
[BUG]: Tensor berserking

### ISSUE THREAD

**Issue by massimiliano-leoni** [FEniCS/dolfinx#2484]
### How to reproduce the bug

The four, innocent-looking lines
```
from dolfinx import fem
import ufl
DG1T = ufl.TensorElement("DG", ufl.tetrahedron, 1)
fs = fem.TensorFunctionSpace(None, DG1T)
```
send `dolfinx` completely berserk: full CPU, 32+GB of allocated RAM and it seemingly hangs forever.

Using instead
```
DG1 = ufl.FiniteElement("DG", ufl.tetrahedron, 1)
fs = fem.FunctionSpace(None, DG1)
```
seems to work just fine.

### Minimal Example (Python)

```Python
from dolfinx import fem
import ufl
DG1T = ufl.TensorElement("DG", ufl.tetrahedron, 1)
fs = fem.TensorFunctionSpace(None, DG1T)
```

### Output (Python)

```bash
When I hit Ctrl+C I get the stack trace

^C---------------------------------------------------------------------------
KeyboardInterrupt                         Traceback (most recent call last)
<ipython-input-1-ac273ac8847d> in <module>
      2 import ufl
      3 DG1T = ufl.TensorElement("DG", ufl.tetrahedron, 1)
----> 4 fs = fem.TensorFunctionSpace(None, DG1T)

~/opt/FEniCS-X/install/local/lib/python3.10/dist-packages/dolfinx/fem/function.py in TensorFunctionSpace(mesh, element, shape, symmetry, restriction)
    587     """Create tensor finite element (composition of scalar elements) function space."""
    588 
--> 589     e = ElementMetaData(*element)
    590     ufl_element = basix.ufl_wrapper.create_tensor_element(
    591         e.family, mesh.ufl_cell().cellname(), e.degree, shape=shape, symmetry=symmetry,

~/opt/FEniCS-X/install/local/lib/python3.10/dist-packages/ufl/finiteelement/finiteelementbase.py in __getitem__(self, index)
    209     def __getitem__(self, index):
    210         "Restrict finite element to a subdomain, subcomponent or topology (cell)."
--> 211         if index in ("facet", "interior"):
    212             from ufl.finiteelement import RestrictedElement
    213             return RestrictedElement(self, index)

KeyboardInterrupt:
```

### Version

main branch

### DOLFINx git commit

2e5c49e6e0ab064d942e9094142960cfc587eab8

### Installation

Manually compiled

**Comment by conpierce8** [comment]
According to the [type hints for `TensorFunctionSpace`](https://github.com/FEniCS/dolfinx/blob/2e5c49e6e0ab064d942e9094142960cfc587eab8/python/dolfinx/fem/function.py#L585), `element` should be either an [`ElementMetaData`](https://github.com/FEniCS/dolfinx/blob/2e5c49e6e0ab064d942e9094142960cfc587eab8/python/dolfinx/fem/function.py#L427) or a `tuple`, not a UFL element. The program enters an infinite loop (with ever-increasing memory usage) because Python tries to unpack the UFL element. The same behavior is triggered with the following three lines:

```python
import ufl
DG1T = ufl.TensorElement("DG", ufl.tetrahedron, 1)
print(*DG1T)
```

I couldn't find any documentation on this, but apparently Python tries to unpack by first looking for an `__iter__` method, and if `__iter__` does not exist it then checks for a [`__getitem__`](https://github.com/FEniCS/ufl/blob/1951bee8d81cfef5f9c6e511944004d93283241b/ufl/finiteelement/finiteelementbase.py#L209) method and repeatedly calls it with `index` starting from 0 and incrementing until an `IndexError` is raised:

```python
class A:
    def __getitem__(self, index):
        if index < 4:
            return index
        else:
            raise IndexError(index)
class B(A):
    def __iter__(self):
        return iter(range(2))
class C:
    def __getitem__(self, index):
        return NotImplemented
print(*A())    # prints "0 1 2 3"
print(*B())    # prints "0 1"
print(*C())    # infinite loop
```

Since `__getitem__` returns `NotImplemented` instead of raising an error, Python proceeds to "unpack" the finite element into an infinite sequence of `NotImplemented`s, hence the high CPU and memory usage and the program hanging forever. The same error occurs in `VectorFunctionSpace` and `TensorFunctionSpace` for scalar, vector, and tensor elements.

Since this results from what appears to be an invalid value passed to `TensorFunctionSpace`, maybe this issue can be closed? On the other hand, it might be good to add some explicit type checking in `VectorFunctionSpace` and `TensorFunctionSpace` to provide a meaningful error message when a UFL element is supplied, if in fact UFL elements are not to be accepted.

**Comment by massimiliano-leoni** [comment]
Believe it or not, I ran into this issue with a "legitimate" use of the library.
Anyway, whatever the reason, this behaviour shouldn't happen. A type check and a meaningful error message look like a reasonable solution to me.

**Comment by garth-wells** [comment]
Fixed by https://github.com/FEniCS/ufl/pull/180.
