### ISSUE TITLE
`io.gmshio.model_to_mesh` doc string is unclear

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2511]
Doc string needs revision. Isn't clear.

**Comment by jorgensd** [comment]
Could you be more specific, what in:
```python
        """Given a Gmsh model, take all physical entities of the highest
        topological dimension and create the corresponding DOLFINx mesh.
        It is assumed that the gmsh model lives on a single rank, and is
        then read into DOLFINx on a single process to be distributed.
        This means that this function should only be called once for
        large problems. It is recommended to save the mesh and
        corresponding tags to XDMFFile after creation for efficient
        access.
        Args:
            comm: The MPI communicator to use for mesh creation
            rank: The rank the Gmsh model is initialized on
            model: The Gmsh model
            gdim: Geometrical dimension of the mesh
            partitioner: Function that computes the parallel
                distribution of cells across MPI ranks
        Returns:
            A triplet (mesh, cell_tags, facet_tags) where cell_tags hold
            markers for the cells, facet tags holds markers for facets
            if found in Gmsh model.
        """
 ```
 is unclear

**Comment by garth-wells** [comment]
- "It is assumed that the gmsh model lives on a single rank": the `model` typehint indicates that all callers need to pass a gmsh model; what 'assumed' means is unclear 
- ". . . and is then read into DOLFINx on a single process to be distributed": What is 'read'?; What is to be distributed?
- "This means that this function should only be called once for large problems" isn't clear

**Comment by jorgensd** [comment]
> - "It is assumed that the gmsh model lives on a single rank": the `model` typehint indicates that all callers need to pass a gmsh model; what 'assumed' means is unclear 
> 

The user has to supply the MPI rank the mesh lives on. When Gmsh is executed with multiple MPI processes, it generates one model per process. Therefore, the most efficient usage of computer resources is to generate a model on a single process, and pass in the rank of that process.

Do you think:
"The GMSH model has to live on the input rank."
Is better?



> - ". . . and is then read into DOLFINx on a single process to be distributed": What is 'read'?; What is to be distributed?

As I stated above, Gmsh runs in serial on each process, thus we extract data on a single rank, and distribute it on the input communicator

> - "This means that this function should only be called once for large problems" isn't clear

We can remove this sentence if you want to. It is because reading a large model on a single rank is not efficient. It would be best to use a parallel suitable format, say XDMF to read in large meshes, as it reads the data in a distributed fashion.
