### ISSUE TITLE
CI test failure in parallel with OpenMPI and PETSc 3.20.0

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#2800]
The test https://github.com/FEniCS/dolfinx/blob/d200635c3efa73f0b44546e5d022c88635f9bc32/python/test/unit/fem/test_nonlinear_assembler.py#L452 fails with OpenMPI and PETSc 3.20.0 in parallel. The error appear to happen when SNES attempts to duplicate a PETSc Vec. 

See https://github.com/FEniCS/dolfinx/blob/d200635c3efa73f0b44546e5d022c88635f9bc32/python/test/unit/fem/test_nonlinear_assembler.py#L527 for a simple call that can trigger the failure.

Problem is not observed with MPICH.

**Comment by francesco-ballarin** [comment]
I had a look to this because my `multiphenicsx` CI was failing after the upgrade to PETSc 3.20, and since I use SNES in several tutorials I thought this was related. (It turned out that it was not, the issue in my demo was some change in the default mumps options).

On my laptop, which uses openmpi, I only observe a failure for the fourth and final mesh, i.e.
```
create_unit_cube(MPI.COMM_WORLD, 3, 5, 4, ghost_mode=GhostMode.shared_facet)
```
Oddly, if I change it to
```
create_unit_cube(MPI.COMM_WORLD, 3, 5, 5, ghost_mode=GhostMode.shared_facet)
```
(notice the change in size for the z axis) the test passes.

**Comment by garth-wells** [comment]
@francesco-ballarin take a look at the code comments in #2802.
