### ISSUE TITLE
Quad Precision FEM in Fenicsx

### ISSUE THREAD

**Issue by RamakrishnanChandran** [FEniCS/dolfinx#2926]
Dear Team,

I'm a Master student in Computational Engineering in FAU Erlangen, Germany. I'm working on Mixed Precision AMG solver for my Master thesis.

I have been using Fenics to extract Matrix and RHS data from the FEM discretization of novel 2D poisson problem with dirichlet BC using Fenics 2019.1.0 library (using python Driver adapting the tutorial code of 2D poisson problem)

I enquired about this in Fenics Discourse. (https://fenicsproject.discourse.group/t/quad-precision-fenics/12979)

Is there any possibility of passing the quad precision template param to the backend C++ code from the python front end such that it could be handled by form complier appropriately.

Thanks and Regards,
Ramakrishnan C.

**Comment by jhale** [comment]
This project sounds very interesting and it would be good if you could keep us informed on how things go as it proceeds.

Regarding your question, FEniCS 2019.1.0 is the legacy version and it does not support mixed/multi-precision operations.

We have built DOLFINx with mixed and multi-precision arithmetic in mind, but we haven't yet explored the potential in terms of implementing real algorithms; for your project I would strongly recommend using the C++ interface to DOLFINx where you have explicit control over the types of both the expansion coefficients and geometry information through templating, rather than Python.

Additionally, we've never tried quad precision, only lower precisions.

**Comment by RamakrishnanChandran** [comment]
Dear Mr. Hale,

Yeah, I will check how I can use the C++ interface to create a driver for
Data extraction for my experiments.

In case you are aware of any tutorials. Could you please give some
suggestions for any tutorial which uses C++ interface directly.

Thanks and regards,
Ramakrishnan C.

**Comment by RamakrishnanChandran** [comment]
Dear Mr. Hale,

Yeah, that is true. The AMG solver (part of GaspiLS, a linear solver
library) which is experimented uses Double and single precision in IR
algorithmic setup.

However, f the Matrix and RHS data from FENICS and L2 error norm
measurement if done in higher precision could help in producing results
which are more reliable. That's the reason, I'm looking for Quad precision.

Anyway, the use of concepts coupled with no quad precision in std library
means even if I use C++ interface of FENICSx for Data extraction, I can't
build the code for quad precision right?

Thanks and Regards,
Ramakrishnan C.

**Comment by jhale** [comment]
You can make a fork and modify the concepts to accept the types you need.

**Comment by RamakrishnanChandran** [comment]
Dear Mr. Hale,

Thanks for your hint. I will try to work on that guidelines and update you.

Thanks and Regards,
Ramakrishnan C.

**Comment by garth-wells** [comment]
You could try with C++23 fixed width floating-point types (https://en.cppreference.com/w/cpp/types/floating-point). I don't know where compiler support is at.
