### ISSUE TITLE
Test Python package build with non-pip frontend

### ISSUE THREAD

**Issue by jhale** [FEniCS/dolfinx#3417]
### Describe new/missing feature

One of our test builds should use an alternative build front-end (i.e. not pip) to check that everything generalises properly.

https://pypi.org/project/build/
https://docs.astral.sh/uv/

**Comment by Saransh-cpp** [comment]
Hi, @jhale. I can see that the build process is quite involved because of the presence of C++ - https://github.com/FEniCS/dolfinx/blob/main/.github/workflows/build-wheels.yml. Should this be parameterised to use both `pip` and `uv` (and subsequently `cibuildwheel[uv]`) or does this require just testing the PyPI package with `uv` (like [conda.yml](https://github.com/FEniCS/dolfinx/blob/main/.github/workflows/conda.yml) does for the conda-forge distributions)?
