### ISSUE TITLE
Avoid need for facet MeshFunction to mark boundary integrals

### ISSUE THREAD

**Issue by garth-wells** [FEniCS/dolfinx#687]
Facet MeshFunction are very large when only a small numbers of facets or just boundary facets need marking. With recent assembler changes it should be possible to just attached a list fo facet indices for each domain.

**Comment by garth-wells** [comment]
MeshFunction removed in #889.

**Comment by marchirschvogel** [comment]
Hello, I am missing the mesh function to create non-int values associated to elements, like in
https://fenicsproject.org/docs/dolfin/2018.1.0/python/demos/tensor-weighted-poisson/documentation.html
Since the meshtags are only allowed to be int, I currently don't see how to transfer this example to dolfin-x.
Do you know if there are any similar demos or a dolfin-x version of this demo?
Thx!
Marc

**Comment by michalhabera** [comment]
Hi Marc,
thanks a lot for trying dolfin-x! Any comments appreciated. I've addressed the issue in https://github.com/FEniCS/dolfinx/pull/1001
Let's just wait for opinions/reimplementation (you can try on a branch in the meantime if needed)
